### ISSUE TITLE
Super Classes

### ISSUE THREAD

**Issue by Trent-Daniel** [Trent-Daniel/Conquistador#1]
This is the file from the video link I shared in the Python Project. When I tried to build it, the output was:

Whiskers is cm tall and 33 kilograms and says10
Traceback (most recent call last):
  File "/Users/trentdaniel/Documents/Test1.py", line 84, in <module>
    spot =Dog("Spot", 53, 27, "Ruff", "Derek")
  File "/Users/trentdaniel/Documents/Test1.py", line 61, in __init__
    super(Dog,self).__init__(name,height,weight,sound)
TypeError: must be type, not classobj
[Finished in 0.0s with exit code 1]

****I don't understand why there was a type error. Do you know how to fix this?

The error occurs on line 61, the line further below which is highlighted in asterisks

import random
import sys
import os

class Animal:
	__name = ""
	__height = 0
	__weight = 0
	__sound = 0

	def __init__(self, name, height, weight, sound):
		self.__name=name
		self.__height=height
		self.__weight=weight
		self.__sound=sound

	def set_name(self, name):
		self.__name=name

	def get_name(self):
		return self.__name

	def set_height(self, height):
		slef.__height=height

	def get_height(self):
		return self.__height

	def set_weight(self,weight):
		self.__weight=weight

	def get_weight(self):
		return self.__weight

	def set_sound(self,sound):
		self.__sound=sound

	def get_sound(self):
		return self.__sound

	def get_type(self):
		print("Animal")

	def toString(self):
		return "{} is cm tall and {} kilograms and says{}" .format(self.__name, 
																   self.__height, 
																   self.__weight,
																   self.__sound)

cat= Animal('Whiskers', 33, 10,'Meow')

print (cat.toString())

class Dog(Animal):
	__owner= None

	def __init__(self, name, height, weight, sound, owner):
		self.__owner=owner
****		super(Dog,self).__init__(name,height,weight,sound)      *********************************

	def set_owner(self, owner):
		self.__owner=owner

	def get_owner(self):
		return self.__owner

	def get_type(self):
		print("Dog")

	def toString(self):
		return "{} is cm tall and {} kilograms and says{} His owner is {}" .format(self.__name, 
																   self.__height, 
																   self.__weight,
																   self.__sound,
																   self.__owner)
	def multiple_sounds(self,how_many=None):
		if how_many is None:
			print(self.get_sound())
		else:
			print(self.get_sound()*how_many)

spot =Dog("Spot", 53, 27, "Ruff", "Derek")

print spot.toString()

class AnimalTesting:
	def get_type(self,animal):
		animal.get_type()

test_animals=AnimalTesting()
test_aniimals.get_type(cat)
test_animals.get_type(spot)

**Comment by Trent-Daniel** [comment]
To solve the problem, the superclass takes the argument "object" and the subclass calls super(subclass_name,self).__init__(args) as in the classes below:

class Person(object):
	__name=None
	__age=None
	__nationality=None

	def __init__(self, name, age, nationality):
		self.__name=name
		self.__age=age
		self.__nationality=nationality

	def get_name(self):
		return self.__name

	def get_age(self):
		return self.__age
	def get_nationality(self):
		return self.__nationality

class Student(Person):
	__grade=None
	__major=None

	def __init__ (self, name, age, nationality, grade, major):
		self.__grade=grade
		self.__major=major
		super(Student,self). __init__ (name,age, nationality)

	def get_grade(self):
		return self.__grade

	def get_major(self):
		return self.__major


Andy=Person('Andy', 16, 'Canadian')

print "The subject is called", Andy.get_name(),". He is", Andy.get_age(),"years old. He is", Andy.get_nationality(),"."

Sarah=Student('Sarah', 16, 'American', 11, 'Social Sciences')

print "The subject is called", Sarah.get_name(), ". She is", Sarah.get_age(), "years old. She is", Sarah.get_nationality(),". She is in grade", Sarah.get_grade(), ". Her major is", Sarah.get_major(),"."
